Fix/issue#124
dionisisvas/training-project pull request #135
Opened 2017-08-30 13:50 UTC by erisara

2017-08-30 15:12 UTC, dionisisvas requested changes

2017-08-30 15:12 UTC, dionisisvas commented on src/main/webapp/app/user-dates/user-dates.component.js
> +    function setTestData() {
Is this needed? (the testItemList)

2017-08-30 16:51 UTC, chris-iri requested changes
Duplicate - ignore

2017-08-30 16:51 UTC, chris-iri approved these changes

2017-08-30 16:53 UTC, chris-iri requested changes
The `user-dates` component should be added inside `profile.template.html` located at */app/views/
The `user-profile` component is unrelated and the same code shouldn't be copied inside it.

2017-08-31 07:50 UTC, dionisisvas commented on src/main/webapp/app/user-profile/user-profile.template.html
> -  </div>
Is this </div> tag need to be deleted or was it deleted by mistake?

2017-08-31 08:14 UTC, dionisisvas approved these changes

2017-08-31 08:14 UTC, dionisisvas approved these changes

2017-08-31 08:16 UTC, merged

2017-08-31 08:17 UTC, dionisisvas commented
Closes Issue #124